In [1]:
import os
import math
import random
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error

import torch
import torch.nn as nn
import torch.nn.functional as F


random.seed(12345)
np.random.seed(42)

warnings.simplefilter("ignore", DeprecationWarning)

In [2]:
series = pd.read_csv('pollution.csv', header=0, index_col=0)
raw_values = series.values

# integer encode wind direction
encoder = LabelEncoder()
raw_values[:,4] = encoder.fit_transform(raw_values[:,4])

In [3]:
series

pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date                                                                          
2010-01-02 00:00:00        129  -16  -4.0  1020.0      SE     1.79     0     0
2010-01-02 01:00:00        148  -15  -4.0  1020.0      SE     2.68     0     0
2010-01-02 02:00:00        159  -11  -5.0  1021.0      SE     3.57     0     0
2010-01-02 03:00:00        181   -7  -5.0  1022.0      SE     5.36     1     0
2010-01-02 04:00:00        138   -7  -5.0  1022.0      SE     6.25     2     0
...                        ...  ...   ...     ...     ...      ...   ...   ...
2014-12-31 19:00:00          8  -23  -2.0  1034.0      NW   231.97     0     0
2014-12-31 20:00:00         10  -22  -3.0  1034.0      NW   237.78     0     0
2014-12-31 21:00:00         10  -22  -3.0  1034.0      NW   242.70     0     0
2014-12-31 22:00:00          8  -22  -4.0  1034.0      NW   246.72     0     0
2014-12-31 23:00:00         12  -21  -3.0  1034.0      NW   249.85     0     0

[43800 rows x 8 columns]

In [4]:
raw_values.shape

(43800, 8)

In [5]:
# create a differenced series
def difference(dataset, interval=1):
    diff = list()
    for i in range(interval, len(dataset)):
        value = dataset[i] - dataset[i-interval]
        diff.append(value)
    return pd.Series(diff)


# transform data to be stationary
diff2 = difference(raw_values, 1)
diff2.shape

diff = pd.DataFrame(raw_values).diff(1).dropna().values

In [6]:
hidden_layers = [35,49,4]
batch_size = 219
dropout = 0.2
seq_len = 25
epochs_pre  = [625,115,933]
epochs_finetune = 197
window_size = 0
features = 8

In [7]:
def create_dataset(dataset, features, look_back=1):
    dataset = np.insert(dataset, [0]*look_back, 0)
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back):
        a = dataset[i:(i+look_back)]
        dataX.append(a)
        dataY.append(dataset[i+look_back])
    dataY = np.array(dataY)
    dataY = np.reshape(dataY, (dataY.shape[0], features))
    dataset = np.concatenate((dataX, dataY), axis=1)
    return dataset
    

dataset2 = diff2.values
dataset2 = create_dataset(dataset2, features, window_size)

In [8]:
dataset = diff

In [9]:
dataset

array([[19, 1, 0.0, ..., 0.8900000000000001, 0, 0],
       [11, 4, -1.0, ..., 0.8899999999999997, 0, 0],
       [22, 4, 0.0, ..., 1.7900000000000005, 1, 0],
       ...,
       [0, 0, 0.0, ..., 4.9199999999999875, 0, 0],
       [-2, 0, -1.0, ..., 4.02000000000001, 0, 0],
       [4, 1, 1.0, ..., 3.1299999999999955, 0, 0]], dtype=object)

In [10]:
dataset.shape

(43799, 8)

In [11]:
data = np.vstack((np.zeros((seq_len, features)), dataset))
data

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [0, 0, 0.0, ..., 4.9199999999999875, 0, 0],
       [-2, 0, -1.0, ..., 4.02000000000001, 0, 0],
       [4, 1, 1.0, ..., 3.1299999999999955, 0, 0]], dtype=object)

In [12]:
# Dropnan = True!
history = np.hstack([data[seq_len-i:-i] for i in range(seq_len, 0, -1)])

In [13]:
n_out = 1
future = np.hstack([data[seq_len+i:] for i in range(n_out)])

In [18]:
future

array([[19, 1, 0.0, ..., 0.8900000000000001, 0, 0],
       [11, 4, -1.0, ..., 0.8899999999999997, 0, 0],
       [22, 4, 0.0, ..., 1.7900000000000005, 1, 0],
       ...,
       [0, 0, 0.0, ..., 4.9199999999999875, 0, 0],
       [-2, 0, -1.0, ..., 4.02000000000001, 0, 0],
       [4, 1, 1.0, ..., 3.1299999999999955, 0, 0]], dtype=object)

In [19]:
agg = np.hstack([history, future[:, 0].reshape(-1, 1)])

In [20]:
agg.shape

(43799, 201)

In [21]:
agg

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 19],
       [0.0, 0.0, 0.0, ..., 0, 0, 11],
       [0.0, 0.0, 0.0, ..., 0, 0, 22],
       ...,
       [-9, -3, -1.0, ..., 0, 0, 0],
       [-6, -1, -1.0, ..., 0, 0, -2],
       [-12, -9, -2.0, ..., 0, 0, 4]], dtype=object)

In [22]:
#convert series to supervised learning
def series_to_supervised(data, features, n_in=1, n_out=1, dropnan=True):
    n_vars = 1 if type(data) is list else data.shape[1]
    x = np.zeros(features, dtype=np.int)
    for i in range(n_in):
        data = np.insert(data, x, 0)
    data = data.reshape(int(data.shape[0]/features), features)
    df = pd.DataFrame(data)
    cols, names = list(), list()
    # input sequence (t-n, ..., t-1)
    for i in range(n_in, 0, -1):
        cols.append(df.shift(i))
        names += [(f"var{j+1}(t-{i})") for j in range(n_vars)]
    # forecast sequence (t, t+1, ..., t+n)
    for i in range(n_out):
        cols.append(df.shift(-i))
        if i == 0:
            names += [(f"var{j+1}(t)") for j in range(n_vars)]
        else:
            names += [(f"var{j+1}(t+{i})") for j in range(n_vars)]
    # Put it all together
    agg = pd.concat(cols, axis=1)
    agg.columns = names
    # drop rows with NaN values
    if dropnan:
        agg.dropna(inplace=True)
    return agg

In [23]:
# frame as supervised learning
# reframed = series_to_supervised(dataset, features, seq_len, 1, dropnan=False)
reframed = agg
# drop = [i for  i in  range(seq_len*features+1,((seq_len+1)*features))]
# reframed.drop(reframed.columns[drop], axis=1, inplace=True)
# reframed = reframed.values

In [26]:
# frame as supervised learning
reframed2 = series_to_supervised(dataset, features, seq_len, 1, dropnan=True)
drop = [i for  i in  range(seq_len*features+1,((seq_len+1)*features))]
reframed2.drop(reframed2.columns[drop], axis=1, inplace=True)
# reframed2 = reframed2.values

In [27]:
reframed2

var1(t-25) var2(t-25) var3(t-25) var4(t-25) var5(t-25) var6(t-25)  \
25             0          0          0          0          0          0   
26             0          0          0          0          0          0   
27             0          0          0          0          0          0   
28             0          0          0          0          0          0   
29             0          0          0          0          0          0   
...          ...        ...        ...        ...        ...        ...   
43819         16          1         -3          1          0       1.79   
43820        -44          5          4          1          1       2.23   
43821         -9         -3         -1          1          0       7.15   
43822         -6         -1         -1          1          0       8.94   
43823        -12         -9         -2          2          0       9.83   

      var7(t-25) var8(t-25) var1(t-24) var2(t-24)  ... var8(t-2) var1(t-1)  \
25             0          0          0          0  ...         0         0   
26             0          0          0          0  ...         0        19   
27             0          0          0          0  ...         0        11   
28             0          0          0          0  ...         0        22   
29             0          0          0          0  ...         0       -43   
...          ...        ...        ...        ...  ...       ...       ...   
43819          0          0        -44          5  ...         0         1   
43820          0          0         -9         -3  ...         0        -2   
43821          0          0         -6         -1  ...         0         2   
43822          0          0        -12         -9  ...         0         0   
43823          0          0          8         -1  ...         0        -2   

      var2(t-1) var3(t-1) var4(t-1) var5(t-1) var6(t-1) var7(t-1) var8(t-1)  \
25            0         0         0         0         0         0         0   
26            1         0         0         0      0.89         0         0   
27            4        -1         1         0      0.89         0         0   
28            4         0         1         0      1.79         1         0   
29            0         0         0         0      0.89         1         0   
...         ...       ...       ...       ...       ...       ...       ...   
43819         0        -1         0         0      4.92         0         0   
43820        -1         0         1         0      5.81         0         0   
43821         1        -1         0         0      5.81         0         0   
43822         0         0         0         0      4.92         0         0   
43823         0        -1         0         0      4.02         0         0   

      var1(t)  
25         19  
26         11  
27         22  
28        -43  
29        -29  
...       ...  
43819      -2  
43820       2  
43821       0  
43822      -2  
43823       4  

[43799 rows x 201 columns]

In [19]:
# scale train and test data to [-1, 1]
def scale(train, test):
    # fit scaler
    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaler = scaler.fit(train)
    # transform train
    train = train.reshape(train.shape[0], train.shape[1])
    train_scaled = scaler.transform(train)
    # transform test
    test = test.reshape(test.shape[0], test.shape[1])
    test_scaled = scaler.transform(test)
    return scaler, train_scaled, test_scaled

In [20]:
# split into train and test sets
train_size = 365*24*4
train, test = reframed[0:train_size], reframed[train_size:]

# transform the scale of the data
scaler, train_scaled, test_scaled = scale(train, test)

# split into input and outputs
x_train,y_train = train_scaled[:,0:-1],train_scaled[:,-1]
x_test,y_test = test_scaled[:,0:-1],test_scaled[:,-1]

# reshape input to be 3D [samples, timesteps, features]
x_train = x_train.reshape(x_train.shape[0], seq_len, features)
x_test = x_test.reshape(x_test.shape[0], seq_len, features)

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(35040, 25, 8) (35040,) (8759, 25, 8) (8759,)


In [22]:
from torch.utils.data import  TensorDataset, DataLoader

In [ ]:
x_train = torch.Tensor(x_train).cuda()
y_train = torch.Tensor(y_train).cuda()
x_test = 

ds = TensorDataset(X, y)

In [22]:
print('\nstart pretraining')
print('===============')

timesteps = x_train.shape[1]
input_dim = x_train.shape[2]
trained_encoder = []
x_train_temp = x_train


start pretraining


In [132]:
hidden_layers, epochs_pre

([35, 49, 4], [625, 115, 933])

In [28]:
x_train_temp.shape

(35040, 25, 8)

In [182]:
class RepeatVector(nn.Module):
    def forward(self, x, h):
        return h.expand(h.shape[0], x.shape[1], h.shape[2])


class LstmAutoEncoder(nn.Module):
    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.encoder = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.repeat = RepeatVector()
        self.decoder = nn.LSTM(hidden_size, input_size, batch_first=True)
        
    def forward(self, x):
        _, (h, _) = self.encoder(x)
        encoded = self.repeat(x, h)
        decoded, _ = self.decoder(encoded)
        return decoded

In [184]:
dims = [8] + hidden_layers
num_stacks = 3

autoencoders = [
    LstmAutoEncoder(*dims[i:i+2])
    for i in range(num_stacks)
]
encoders = nn.Sequential(*[ae.encoder for ae in autoencoders])

In [185]:
# Pre-Training
optimizer = torch.optim.Adam(autoencoders[0].parameters())
autoencoders[0]

LstmAutoEncoder(
  (encoder): LSTM(8, 35, batch_first=True)
  (repeat): RepeatVector()
  (decoder): LSTM(35, 8, batch_first=True)
)

In [186]:
autoencoders[0]

LstmAutoEncoder(
  (encoder): LSTM(8, 35, batch_first=True)
  (repeat): RepeatVector()
  (decoder): LSTM(35, 8, batch_first=True)
)

In [187]:
for ae in autoencoders:
    ae.cuda()

[Parameter containing:
 tensor([[-0.1473,  0.0254, -0.0820,  ..., -0.0353, -0.1494,  0.0030],
         [ 0.0198, -0.0023, -0.0761,  ..., -0.0943, -0.0779, -0.1049],
         [-0.0489,  0.1497,  0.1230,  ..., -0.0113, -0.0892,  0.1646],
         ...,
         [ 0.0802, -0.0762,  0.1378,  ...,  0.0467,  0.1330, -0.0091],
         [ 0.0066, -0.0176, -0.0699,  ...,  0.0135,  0.0646,  0.0934],
         [ 0.1136,  0.0310,  0.1379,  ..., -0.1322,  0.1012,  0.1176]],
        device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([[ 0.0489,  0.0450, -0.1117,  ..., -0.0256,  0.0055, -0.0816],
         [ 0.1598,  0.0276,  0.0714,  ...,  0.1052, -0.0063, -0.0394],
         [ 0.1009,  0.0175,  0.1672,  ..., -0.0585,  0.0738,  0.1347],
         ...,
         [ 0.0102,  0.0446, -0.0294,  ..., -0.1652, -0.1456, -0.0364],
         [-0.0754,  0.1286,  0.0658,  ..., -0.1608,  0.0705, -0.1141],
         [ 0.1218,  0.0121, -0.0180,  ...,  0.1200,  0.0105,  0.1645]],
        device='cuda:0', r